steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/binge-bundler-repo/binge-bundler-image:tag1 .
  automapSubstitutions: true
options:
 logging: CLOUD_LOGGING_ONLY
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/binge-bundler-repo/binge-bundler-image:tag1'