name: Test and Check Secrets

on:
  push:
    branches: [main]

jobs:
  example-job:
    name: Log secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log secrets
        run: |
          echo "apiKey: ${apiKey}"
          echo "bearerToken: ${bearerToken}"
          echo "baseUrl: ${baseUrl}"
        env:
          apiKey: ${{ secrets.APIKEY }}
          bearerToken: ${{ secrets.BEARERTOKEN }}
          baseUrl: ${{ secrets.BASEURL }}
